### ISSUE TITLE
build apk error

### ISSUE THREAD

**Issue by kaishijeng** [mehtaViraj/locationSharing_flutter#1]
I got the following error when do "flutter build apk":

Running "flutter pub get" in locationSharing_flutter...          1,613ms
The plugin `google_maps_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2
embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Warning: The plugin location_permissions requires Android SDK version 29.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /home/ubuntu/Flutter/locationSharing_flutter/android/app/build.gradle:
android {
  compileSdkVersion 29
  ...
}

lib/dashboard_builder.dart:38:13: Error: No named parameter with the name 'title'.
            title: new Text('Find'),
            ^^^^^
../../Applications/flutter/packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart:25:9: Context: Found this candidate, but the arguments don't match.
  const BottomNavigationBarItem({
        ^^^^^^^^^^^^^^^^^^^^^^^
lib/dashboard_builder.dart:42:13: Error: No named parameter with the name 'title'.
            title: new Text('Social'),
            ^^^^^
../../Applications/flutter/packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart:25:9: Context: Found this candidate, but the arguments don't match.
  const BottomNavigationBarItem({
        ^^^^^^^^^^^^^^^^^^^^^^^
../../Applications/flutter/.pub-cache/hosted/pub.dartlang.org/platform-2.2.1/lib/src/interface/local_platform.dart:45:41: Error: Member not found: 'packageRoot'.
  String get packageRoot => io.Platform.packageRoot;
                                        ^^^^^^^^^^^

         *********************************************************
WARNING: This version of google_maps_flutter will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* Where:
Script '/home/ubuntu/Applications/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/ubuntu/Applications/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Running Gradle task 'assembleRelease'...                           12.7s
Gradle task assembleRelease failed with exit code 1

My flutter version info:

Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (2 weeks ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

Any idea how to fix them?

Thanks,

**Comment by mehtaViraj** [comment]
This repo is relatively old, so a few changes will probably need to be made.

1. Replace "title" in the BottomNavigationBarItem with "label"
2. Upgrade Gradle
3. Upgrade Kotlin SDK (these will be in pubspec.yaml or build.gradle - the errors will pop up as you fix things one by one)
4. set compileSDK to 31
5. The server IP is hard-coded into [special_functions.dart](https://github.com/mehtaViraj/locationSharing_flutter/blob/master/lib/special_functions.dart). Once you have your own server running from the provided server files, you will need to update the same.

There may be other deprecated sections besides these, I haven't looked at this project for over at least a year

**Comment by kaishijeng** [comment]
Thanks for a reply, I don't think I can make it work because there are too many changes required.
Do you plan to upgrade it with the latest flutter?

Thanks,
